package gui.controller;

import be.Personnel;
import bll.PersonnelManager;
import io.github.palexdev.materialfx.controls.MFXButton;
import io.github.palexdev.materialfx.controls.MFXPasswordField;
import io.github.palexdev.materialfx.controls.MFXTextField;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

/**
 * Controller class for the login view.
 */
public class LoginViewController {

    // FXML elements injected from the corresponding FXML file
    @FXML
    private MFXPasswordField txtFieldPassword;
    @FXML
    private MFXTextField txtFieldUsername;
    @FXML
    private MFXButton btnLogin1;
    @FXML
    private MFXButton btnLogin;

    // Instance of PersonnelManager for handling Personnel-related operations
    private PersonnelManager personnelManager = new PersonnelManager();

    /**
     * Constructor for LoginViewController.
     *
     * @throws IOException if an I/O error occurs.
     */
    public LoginViewController() throws IOException {
    }

    /**
     * Event handler for the login button.
     *
     * @param actionEvent The action event generated by clicking the login button.
     * @throws Exception if an error occurs during login validation or view loading.
     */
    @FXML
    private void handleLogin(ActionEvent actionEvent) throws Exception {
        // Retrieve the username and password entered by the user
        String userName = txtFieldUsername.getText();
        String userPassword = txtFieldPassword.getText();

        // Validate the user credentials
        Personnel personnelLogged = personnelManager.validatePersonnel(userName.toLowerCase(), userPassword);
        if (!(personnelLogged == null)) {
            // if it matches you are logged in
            if (personnelLogged.getRoleId() == 1) {
                // Load the admin view if the user is an admin
                FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/MainView.fxml"));
                Parent secondWindow = loader.load();
                Stage newStage = new Stage();
                newStage.setTitle("Admin Page");
                MainViewController controller = loader.getController();
                controller.setup();
                controller.setOperator(personnelLogged);
                Scene scene = new Scene(secondWindow);
                newStage.setScene(scene);

                // Check if the current window is maximized
                Stage currentStage = (Stage) btnLogin.getScene().getWindow();
                if (currentStage.isMaximized()) {
                    newStage.setMaximized(true); // Maximize the new window
                }

                newStage.show();
                currentStage.hide();

            }
            if (personnelLogged.getRoleId() == 2) {
                // Load the coordinator view if the user is a coordinator
                FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/KoordinatorPage.fxml"));
                Parent secondWindow = loader.load();
                Stage newStage = new Stage();
                newStage.setTitle("Coordinator Page");
                Scene scene = new Scene(secondWindow);
                newStage.setScene(scene);

                // Check if the current window is maximized
                Stage currentStage = (Stage) btnLogin.getScene().getWindow();
                if (currentStage.isMaximized()) {
                    newStage.setMaximized(true); // Maximize the new window
                }

                newStage.show();
                currentStage.hide();

            }
        } else {
            // Display a message for incorrect password or username
            txtFieldUsername.setText("");
            txtFieldPassword.setText("");
            txtFieldUsername.setPromptText("Incorrect Password or Username");
        }
    }

    /**
     * Event handler for the forgot password button (currently empty).
     *
     * @param actionEvent The action event generated by clicking the forgot password button.
     */
    @FXML
    private void handleForgotPassword(ActionEvent actionEvent) {
        // Placeholder method for handling forgot password functionality
    }
}
